#!/bin/bash

SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"
SCRIPTPATH/down

# Boot picom or compton if it exists
if [ -x "$(command -v picom)" ]; then
    picom &> /dev/null &
elif [ -x "$(command -v compton)" ]; then
  compton &> /dev/null & 
fi

#set the theme.ron config
leftwm-command "LoadTheme $SCRIPTPATH/theme.ron"

#set background
if [ -x "$(command -v feh)" ]; then
  feh --bg-scale $SCRIPTPATH/wallpaper.jpg
fi

#polybar
if [ -x "$(command -v polybar)" ]; then
    # Terminate already running bar instances
    killall -q polybar

    # Wait until the processes have been shut down
    while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

    # Launch Polybar for each monitor
    for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
        MONITOR=$m polybar --reload main &
    done
fi

