;; ┌────────────────────────────────────────────────────────────┐
;; │░█▀█░█▀█░█░░░█░█░█▀▄░█▀█░█▀▄░░░░░░░░░█▀▀░█▀█░█▀█░█▀▀░▀█▀░█▀▀│
;; │░█▀▀░█░█░█░░░░█░░█▀▄░█▀█░█▀▄░░░░▀░░░░█░░░█░█░█░█░█▀▀░░█░░█░█│
;; │░▀░░░▀▀▀░▀▀▀░░▀░░▀▀░░▀░▀░▀░▀░░░░▀░░░░▀▀▀░▀▀▀░▀░▀░▀░░░▀▀▀░▀▀▀│
;; │░Created░By░Jay Baker @jamesbaker  ░░░░░░░░░░░░░░░░░░░░░░░░░│
;; │░Forked from a theme by░Aditya░Shakya░@adi1090x░░░░░░░░░░░░░│
;; └────────────────────────────────────────────────────────────┘

[module/date]
type = internal/date
interval = 1.0
time = %I:%M:%S %p
date-alt = %A, %d %B %Y
time-alt = %I:%M:%S %p
format = <label>
format-prefix-foreground = ${color.blue}
label = %date% %time%

[module/wired-network]
type = internal/network
interface = eth0

[module/wireless-network]
type = internal/network
interface = wlan0

[module/network]
type = internal/network
interface = wlan0
interval = 1.0
accumulate-stats = true
unknown-as-up = true
format-connected = <label-connected>
format-connected-prefix = 
format-connected-prefix-foreground = ${color.purple}
format-disconnected = <label-disconnected>
format-disconnected-prefix = 
format-disconnected-prefix-foreground = ${color.orange}
label-connected = "%{A1:networkmanager_dmenu &:} %essid% %{F#6C77BB}%{F-} %downspeed%%{A}"
label-disconnected = "%{A1:networkmanager_dmenu &:} Offline%{A}"

[module/workspaces]
type = internal/xworkspaces
enable-click = true
enable-scroll = true
label-active-foreground = ${color.pink}
label-occupied-foreground = ${color.cyan}
label-urgent-foreground = ${color.red}
label-empty-foreground = ${color.foreground}
