;;  ────────────────────────────────────────────────────────────┐
;; │░█▀█░█▀█░█░░░█░█░█▀▄░█▀█░█▀▄░░░░░░░░░█▀▀░█▀█░█▀█░█▀▀░▀█▀░█▀▀│
;; │░█▀▀░█░█░█░░░░█░░█▀▄░█▀█░█▀▄░░░░▀░░░░█░░░█░█░█░█░█▀▀░░█░░█░█│
;; │░▀░░░▀▀▀░▀▀▀░░▀░░▀▀░░▀░▀░▀░▀░░░░▀░░░░▀▀▀░▀▀▀░▀░▀░▀░░░▀▀▀░▀▀▀│
;; │░Created░By░Jay Baker @jamesbaker  ░░░░░░░░░░░░░░░░░░░░░░░░░│
;; │░Forked from a theme by░Aditya░Shakya░@adi1090x░░░░░░░░░░░░░│
;; └────────────────────────────────────────────────────────────┘

[module/pipewire]
type = custom/script
tail = true
format-underline = ${colors.cyan}
label-padding = 0
label-foreground = ${colors.foreground}

exec = ~/.config/polybar/pipewire/pipewire-control.bash --icons-volume "%{T2}%{T-} ,%{T2}%{T-} " --icon-muted "%{T2}%{T-} " listen
click-right = exec pavucontrol &
click-left = ~/.config/polybar/pipewire/pipewire-control.bash togmute
scroll-up = ~/.config/polybar/pipewire/pipewire-control.bash --volume-max 130 up
scroll-down = ~/.config/polybar/pipewire/pipewire-control.bash --volume-max 130 down

[module/sep]
type = custom/text
content = |
content-foreground = ${color.sep}

[module/appmenu]
type = custom/text
content = "%{T3}%{T-}"
click-left = "~/.config/polybar/launcher/launcher.sh"

[module/powermenu]
type = custom/text
content = "%{T2}%{T-}"
click-left = ~/.config/polybar/powermenu/powermenu.sh

[module/dunst]
type = custom/ipc
initial = 1
format-foreground = ${colors.yellow}

hook-0 = echo "%{A1:dunstctl set-paused true && polybar-msg hook dunst 2:}%{T2}%{T-}%{A}" &
hook-1 = echo "%{A1:dunstctl set-paused false && polybar-msg hook dunst 1:}%{T2}%%{T-}{A}" &
