[[repos]]
url = "localhost"
name = "LOCAL"
definitions_version = 1

[[repos.themes]]
name = "Arch"
directory = "/home/losseheil/.config/leftwm/themes/Arch"
version = "0.0.0"
leftwm_versions = "*"
current = true
